spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/product_db
    username: root
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never

server:
  port: 8080
  

payment:
  api:
    url: https://your-beeceptor-url.free.beeceptor.com 

logging:
  level:
    root: DEBUG
    com.product.assignment: DEBUG 